### ISSUE TITLE
fluentd CrashLoopBackOff if one output target is not available

### ISSUE THREAD

**Issue by eumel8** [kube-logging/logging-operator#1169]
**Describe the bug**:
In a shared cluster environment we have different customer with different flows/outputs, where the user can configure the log output from his application and export them to ElasticSearch service or whatever. Everytime if one target is not available, fluentd crashs and the whole cluster logging is blocked, which affects all customer of this cluster.

**Expected behaviour**:
fluentd is informed about the unavailable target,stores the logs, try to reconnect but don't crash

**Steps to reproduce the bug**:
Configure Output with Logstash/Elasticsearch target, start logging, kill target service

**Additional context**:
Not sure if there is a configuration option to prevent this issue.

**Environment details**:
- Kubernetes version (e.g. v1.15.2): v1.20.15
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc): Rancher RKE1
- logging-operator version (e.g. 2.1.1): rancher-logging-100.1.3+up3.17.7, fluentd:v1.14.6-alpine-5
- Install method (e.g. helm or static manifests): Helm
- Logs from the misbehaving component (and any other relevant logs):

```
  2023-01-23 07:38:48 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/gelf-3.0.0/lib/gelf/transport/tcp.rb:31:in `initialize'
  2023-01-23 07:38:48 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/gelf-3.0.0/lib/gelf/transport/tcp.rb:31:in `new'
  2023-01-23 07:38:48 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/gelf-3.0.0/lib/gelf/transport/tcp.rb:31:in `connect'
  2023-01-23 07:38:48 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/gelf-3.0.0/lib/gelf/transport/tcp.rb:15:in `block (2 levels) in addresses='
  2023-01-23 07:38:48 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/gelf-3.0.0/lib/gelf/transport/tcp.rb:15:in `map'
  2023-01-23 07:38:48 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/gelf-3.0.0/lib/gelf/transport/tcp.rb:15:in `block in addresses='
  2023-01-23 07:38:48 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/gelf-3.0.0/lib/gelf/transport/tcp.rb:13:in `tap'
  2023-01-23 07:38:48 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/gelf-3.0.0/lib/gelf/transport/tcp.rb:13:in `addresses='
  2023-01-23 07:38:48 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/gelf-3.0.0/lib/gelf/transport/tcp.rb:9:in `initialize'
  2023-01-23 07:38:48 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/gelf-3.0.0/lib/gelf/notifier.rb:138:in `new'
  2023-01-23 07:38:48 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/gelf-3.0.0/lib/gelf/notifier.rb:138:in `create_sender'
  2023-01-23 07:38:48 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/gelf-3.0.0/lib/gelf/notifier.rb:36:in `initialize'
  2023-01-23 07:38:48 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluent-plugin-gelf-hs-1.0.8/lib/fluent/plugin/out_gelf.rb:52:in `new'
  2023-01-23 07:38:48 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluent-plugin-gelf-hs-1.0.8/lib/fluent/plugin/out_gelf.rb:52:in `start'
  2023-01-23 07:38:48 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.14.6/lib/fluent/compat/call_super_mixin.rb:42:in `start'
  2023-01-23 07:38:48 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.14.6/lib/fluent/root_agent.rb:203:in `block in start'
  2023-01-23 07:38:48 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.14.6/lib/fluent/root_agent.rb:182:in `block (2 levels) in lifecycle'
  2023-01-23 07:38:48 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.14.6/lib/fluent/agent.rb:121:in `block (2 levels) in lifecycle'
  2023-01-23 07:38:48 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.14.6/lib/fluent/agent.rb:120:in `each'
  2023-01-23 07:38:48 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.14.6/lib/fluent/agent.rb:120:in `block in lifecycle'
  2023-01-23 07:38:48 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.14.6/lib/fluent/agent.rb:113:in `each'
  2023-01-23 07:38:48 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.14.6/lib/fluent/agent.rb:113:in `lifecycle'
  2023-01-23 07:38:48 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.14.6/lib/fluent/root_agent.rb:181:in `block in lifecycle'
  2023-01-23 07:38:48 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.14.6/lib/fluent/root_agent.rb:178:in `each'
  2023-01-23 07:38:48 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.14.6/lib/fluent/root_agent.rb:178:in `lifecycle'
  2023-01-23 07:38:48 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.14.6/lib/fluent/root_agent.rb:202:in `start'
  2023-01-23 07:38:48 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.14.6/lib/fluent/engine.rb:248:in `start'
  2023-01-23 07:38:48 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.14.6/lib/fluent/engine.rb:147:in `run'
  2023-01-23 07:38:48 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.14.6/lib/fluent/supervisor.rb:720:in `block in run_worker'
  2023-01-23 07:38:48 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.14.6/lib/fluent/supervisor.rb:971:in `main_process'
  2023-01-23 07:38:48 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.14.6/lib/fluent/supervisor.rb:711:in `run_worker'
  2023-01-23 07:38:48 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.14.6/lib/fluent/command/fluentd.rb:376:in `<top (required)>'
  2023-01-23 07:38:48 +0000 [error]: #0 /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
  2023-01-23 07:38:48 +0000 [error]: #0 /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
  2023-01-23 07:38:48 +0000 [error]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.14.6/bin/fluentd:15:in `<top (required)>'
  2023-01-23 07:38:48 +0000 [error]: #0 /usr/bin/fluentd:23:in `load'
  2023-01-23 07:38:48 +0000 [error]: #0 /usr/bin/fluentd:23:in `<main>'
2023-01-23 07:38:48 +0000 [error]: #0 unexpected error error_class=Errno::ECONNREFUSED error="Connection refused - connect(2) for \"xxxx.xxxx.svc.cluster.local\" port 12202"
  2023-01-23 07:38:48 +0000 [error]: #0 suppressed same stacktrace
2023-01-23 07:38:48 +0000 [error]: Worker 0 finished unexpectedly with status 1
```

/kind bug

**Comment by steffeneichler** [comment]
same errors here. :-(

**Comment by aslafy-z** [comment]
This looks like an issue with the [fluent-plugin-gelf-hs plugin](https://github.com/hotschedules/fluent-plugin-gelf-hs) or the [gelf gem](https://github.com/graylog-labs/gelf-rb) to me. I see these plugins were not updated for years now. 
[Here's a similar issue on a similar plugin](https://github.com/emsearcy/fluent-plugin-gelf/issues/28) and the [upstream one](https://github.com/graylog-labs/gelf-rb/issues/84), looks like the current workaround is to move to the UDP mode. I'm pretty sure this causes others issues like tho. Not sure we can do anything for this on logging-operator side.

**Comment by eumel8** [comment]
HI @aslafy-z ,
thanks for the hints. I think UDP isn't an option if you want to ensure that the logs are really delivered. The idea would be, the Operator  has a sidecar/watcher to monitor the targets and deactivate the Output if the target is not reachable.
Not easy to implement.

**Comment by steffeneichler** [comment]
An endpoint validation before config reload inside of fluentd pods could help to reduce problems.There is a config syntax check Pod implemented. But sytactically correctness does not help if an endpoint is not reachable or not ready to receive data for any reason.An invalid endpoint is mostly no problem after fluentd has initialized correctly. But if an endpoint is not there correctly on config reload, the fluentd won‘t become healthy and end up in crash loop.Am 10.02.2023 um 08:32 schrieb Frank Kloeker ***@***.***>:﻿
HI @aslafy-z ,
thanks for the hints. I think UDP isn't an option if you want to ensure that the logs are really delivered. The idea would be, the Operator  has a sidecar/watcher to monitor the targets and deactivate the Output if the target is not reachable.
Not easy to implement.

**Comment by aslafy-z** [comment]
Slack discussion: https://community-banzaicloud.slack.com/archives/CGMPPBZBK/p1676205626977849?thread_ts=1676205626.977849&cid=CGMPPBZBK

**Comment by tarokkk** [comment]
Just to be transparent I'll answer here as well not just on slack. The problem here is how the output plugin handles the configuration check. I'll look into the plugin and see whether there is an easy workaround to make init time endpoint checking optional. That would result in a way you expect (runtime error and not panic exit)

**Comment by steffeneichler** [comment]
non working endpoints should be skipped and not influence log processing for other outputs.

**Comment by pepov** [comment]
this is a generic issue with fluentd output plugins, not something we can do on the operator side
