### ISSUE TITLE
Lock docker image used by a logging-operator release

### ISSUE THREAD

**Issue by terjesannum** [kube-logging/logging-operator#1890]
Yesterday we experienced a problem with some fluentd pods not starting. The problem seemed to be something with the prometheus plugin config:
```
[error]: #0 unexpected error error_class=URI::InvalidURIError error="bad URI(is not URI?): \"http://:::24231\""
...
[error]: #0 /usr/local/bundle/gems/fluent-plugin-prometheus-2.2.0/lib/fluent/plugin/in_prometheus.rb:113:in `start'
```

This only happend on some fluentd pods, and inspecting those we found that they used another docker image:

Working:
```
Image:           ghcr.io/kube-logging/fluentd:v1.16-4.11-full
Image ID:        ghcr.io/kube-logging/fluentd@sha256:0fc210e2164dbf126a45a82bfb954c68b61de178b765ed9d69c94b9ce906fc9f
```

Failing:
```
Image:           ghcr.io/kube-logging/fluentd:v1.16-4.11-full
Image ID:        ghcr.io/kube-logging/fluentd@sha256:5ad73c43b4cddfdfd792e0da1671792624b98194143aad0545e9256571fee280
```

That failing image was pulled on new nodes that didn't have the old `fluentd:v1.16-4.11-full` already pulled when the autoscaler wanted to scale up.

So is it possible change the logging-operator so that a release always will use the same docker images to avoid these surprises?

At the moment we have to override the image tag to `v1.16-4.11-full-build.169`. The tag used by the operator (`v1.16-4.11-full`) has been moved to `v1.16-4.11-full-build.171`, which doesn't work with the prometheus plugin.

**Comment by csatib02** [comment]
Hey @terjesannum,

Would you be able to send as an example of the fluentd-config or logging-resource you deploy? So we can better investigate this.

**Comment by terjesannum** [comment]
Here is the logging resource:

```yaml
apiVersion: logging.banzaicloud.io/v1beta1
kind: Logging
metadata:
  annotations:
    meta.helm.sh/release-name: logging
    meta.helm.sh/release-namespace: nais-system
  creationTimestamp: "2024-12-18T06:32:47Z"
  generation: 17
  labels:
    app.kubernetes.io/managed-by: Helm
  name: logging
  resourceVersion: "44010357"
  uid: cd24defd-a637-4411-ac60-b6bae479c7ee
spec:
  controlNamespace: nais-system
  enableRecreateWorkloadOnImmutableFieldChange: true
  fluentd:
    configReloaderResources:
      requests:
        cpu: 10m
        memory: 50Mi
    disablePvc: true
    image:
      tag: v1.16-4.11-full-build.169
    labels:
      app: fluentd
    metrics:
      interval: 1m
      prometheusRules: false
      serviceMonitor: true
      serviceMonitorConfig:
        honorLabels: true
        relabelings:
        - action: replace
          regex: (.+)
          sourceLabels:
          - __meta_kubernetes_pod_name
          targetLabel: instance
      timeout: 10s
    resources:
      limits:
        memory: 1Gi
      requests:
        cpu: 500m
        memory: 512M
    security:
      podSecurityContext:
        fsGroup: 101
        runAsNonRoot: true
        runAsUser: 100
        seccompProfile:
          type: RuntimeDefault
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
          - ALL
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
```

**Comment by terjesannum** [comment]
Here is the full error:
```
2024-12-18 10:57:40 +0000 [error]: #0 unexpected error error_class=URI::InvalidURIError error="bad URI(is not URI?): \"http://:::24231\""
  2024-12-18 10:57:40 +0000 [error]: #0 /usr/local/lib/ruby/3.2.0/uri/rfc3986_parser.rb:66:in `split'
  2024-12-18 10:57:40 +0000 [error]: #0 /usr/local/lib/ruby/3.2.0/uri/rfc3986_parser.rb:71:in `parse'
  2024-12-18 10:57:40 +0000 [error]: #0 /usr/local/lib/ruby/3.2.0/uri/common.rb:193:in `parse'
  2024-12-18 10:57:40 +0000 [error]: #0 /usr/local/lib/ruby/3.2.0/uri/common.rb:722:in `URI'
  2024-12-18 10:57:40 +0000 [error]: #0 /usr/local/bundle/gems/fluentd-1.16.6/lib/fluent/plugin_helper/http_server/server.rb:40:in `initialize'
  2024-12-18 10:57:40 +0000 [error]: #0 /usr/local/bundle/gems/fluentd-1.16.6/lib/fluent/plugin_helper/http_server.rb:69:in `new'
  2024-12-18 10:57:40 +0000 [error]: #0 /usr/local/bundle/gems/fluentd-1.16.6/lib/fluent/plugin_helper/http_server.rb:69:in `http_server_create_http_server'
  2024-12-18 10:57:40 +0000 [error]: #0 /usr/local/bundle/gems/fluent-plugin-prometheus-2.2.0/lib/fluent/plugin/in_prometheus.rb:113:in `start'
  2024-12-18 10:57:40 +0000 [error]: #0 /usr/local/bundle/gems/fluentd-1.16.6/lib/fluent/root_agent.rb:203:in `block in start'
  2024-12-18 10:57:40 +0000 [error]: #0 /usr/local/bundle/gems/fluentd-1.16.6/lib/fluent/root_agent.rb:192:in `block (2 levels) in lifecycle'
  2024-12-18 10:57:40 +0000 [error]: #0 /usr/local/bundle/gems/fluentd-1.16.6/lib/fluent/root_agent.rb:191:in `each'
  2024-12-18 10:57:40 +0000 [error]: #0 /usr/local/bundle/gems/fluentd-1.16.6/lib/fluent/root_agent.rb:191:in `block in lifecycle'
  2024-12-18 10:57:40 +0000 [error]: #0 /usr/local/bundle/gems/fluentd-1.16.6/lib/fluent/root_agent.rb:178:in `each'
  2024-12-18 10:57:40 +0000 [error]: #0 /usr/local/bundle/gems/fluentd-1.16.6/lib/fluent/root_agent.rb:178:in `lifecycle'
  2024-12-18 10:57:40 +0000 [error]: #0 /usr/local/bundle/gems/fluentd-1.16.6/lib/fluent/root_agent.rb:202:in `start'
  2024-12-18 10:57:40 +0000 [error]: #0 /usr/local/bundle/gems/fluentd-1.16.6/lib/fluent/engine.rb:248:in `start'
  2024-12-18 10:57:40 +0000 [error]: #0 /usr/local/bundle/gems/fluentd-1.16.6/lib/fluent/engine.rb:147:in `run'
  2024-12-18 10:57:40 +0000 [error]: #0 /usr/local/bundle/gems/fluentd-1.16.6/lib/fluent/supervisor.rb:617:in `block in run_worker'
  2024-12-18 10:57:40 +0000 [error]: #0 /usr/local/bundle/gems/fluentd-1.16.6/lib/fluent/supervisor.rb:962:in `main_process'
  2024-12-18 10:57:40 +0000 [error]: #0 /usr/local/bundle/gems/fluentd-1.16.6/lib/fluent/supervisor.rb:608:in `run_worker'
  2024-12-18 10:57:40 +0000 [error]: #0 /usr/local/bundle/gems/fluentd-1.16.6/lib/fluent/command/fluentd.rb:372:in `<top (required)>'
  2024-12-18 10:57:40 +0000 [error]: #0 <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
  2024-12-18 10:57:40 +0000 [error]: #0 <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
  2024-12-18 10:57:40 +0000 [error]: #0 /usr/local/bundle/gems/fluentd-1.16.6/bin/fluentd:15:in `<top (required)>'
  2024-12-18 10:57:40 +0000 [error]: #0 /usr/local/bundle/bin/fluentd:25:in `load'
  2024-12-18 10:57:40 +0000 [error]: #0 /usr/local/bundle/bin/fluentd:25:in `<main>'
```

**Comment by pepov** [comment]
We've released a fix in 5.0.1 and rolled back the related change in 4.11.4, please feel free to reopen if you still experience the issue with any of the above releases.

According to the version lock question, we've decided to disable the updates to gem dependencies and will only consider the update in case there are any security updates announced.

We've also added a note to our release page so that users can decide if they want to pin to a specific build number to avoid surprises.

Intermittent changes to existing images will be announced on our community channels:
https://kube-logging.dev/docs/community/

Lastly, we plan to migrate the fluentd image build to the logging operator repository and publish releases along with the Logging Operator so that their versions are aligned completely.

We apologize for the inconvenience this has made!
